defaults: 
  - _self_
  - global_paths: default.yaml
  - experiment: train/GFP-hard-unsmoothed

task_name: ${experiment.task_name}

data:
  task: ${task_name}
  batch_size: 1024
  num_workers: 8
  seed: 420
  alphabet: ARNDCQEGHILKMFPSTWYV 
  sequence_column: sequence
  weighted_sampling: True

model:
  optimizer:
    lr: 0.0001
    weight_decay: 0.0001

callbacks:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${global_paths.root_dir}/ckpt/${data.task}
  filename: epoch_{epoch:03d}
  monitor: train_sr
  mode: max
  save_top_k: 1
  save_last: True
  
trainer:
  max_epochs: 100
  accelerator: gpu
  log_every_n_steps: 1